# AWS CLI 
DEF_PROFILE = 'default' # Default profile

# Stack fields summary 
STACKS = 'Stacks'
STACK_SUMMARIES = 'StackSummaries'
STACK_NAME = 'StackName'
STACK_ID = 'StackId'
CREATION_TIME = 'CreationTime'
LAST_UPDATD_TIME = 'LastUpdatedTime'
DELETION_TIME = 'DeletionTime'
STACK_STATUS = 'StackStatus'
STACK_STATUS_REASON = 'StackStatusReason'
PARENT_ID = 'ParentId'
ROOT_ID = 'RootId'
DRIFT_INFORMATION ='DriftInformation'
ENABLE_TERMINATION_PROTECTION = 'EnableTerminationProtection'

# More stack fields
DESCRIPTION = 'Description'
TIMEOUT_IN_MINUTES = 'TimeoutInMinutes'
ROLE_ARN = 'RoleARN'
PARAMETERS = 'Parameters'
TAGS = 'Tags'
ENABLE_TERMINATION_PROTECTION= 'EnableTerminationProtection'
OUTPUTS = 'Outputs'
CAPABILITIES = 'Capabilities'
NOTIFICATION_ARNS = 'NotificationARNs'
DISABLE_ROLLBACK = 'DisableRollback'
ROLLBACK_CONFIGURATION = 'RollbackConfiguration'


STACK_SUMMARY_FILEDS = [STACK_ID, 
                    CREATION_TIME,
                    LAST_UPDATD_TIME,
                    DELETION_TIME,
                    STACK_STATUS,
                    STACK_STATUS_REASON,
                    PARENT_ID,
                    ROOT_ID,
                    DRIFT_INFORMATION]

STACK_DETAIL_FILEDS = STACK_SUMMARY_FILEDS + [DESCRIPTION,
                                        TIMEOUT_IN_MINUTES,
                                        ROLE_ARN,
                                        PARAMETERS,
                                        TAGS,
                                        ENABLE_TERMINATION_PROTECTION,
                                        OUTPUTS,
                                        CAPABILITIES,
                                        NOTIFICATION_ARNS,
                                        DISABLE_ROLLBACK,
                                        ROLLBACK_CONFIGURATION]

# Stack status filters
CREATE_IN_PROGRESS = 'CREATE_IN_PROGRESS'
CREATE_FAILED = 'CREATE_FAILED'
CREATE_COMPLETE = 'CREATE_COMPLETE'
ROLLBACK_IN_PROGRESS = 'ROLLBACK_IN_PROGRESS'
ROLLBACK_FAILED = 'ROLLBACK_FAILED'
ROLLBACK_COMPLETE = 'ROLLBACK_COMPLETE'
DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS'
DELETE_FAILED = 'DELETE_FAILED'
DELETE_COMPLETE = 'DELETE_COMPLETE'
UPDATE_IN_PROGRESS = 'UPDATE_IN_PROGRESS'
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS = 'UPDATE_COMPLETE_CLEANUP_IN_PROGRESS'
UPDATE_COMPLETE = 'UPDATE_COMPLETE'
UPDATE_ROLLBACK_IN_PROGRESS = 'UPDATE_ROLLBACK_IN_PROGRESS'
UPDATE_ROLLBACK_FAILED = 'UPDATE_ROLLBACK_FAILED'
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS = 'UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS'
UPDATE_ROLLBACK_COMPLETE = 'UPDATE_ROLLBACK_COMPLETE'
REVIEW_IN_PROGRESS = 'REVIEW_IN_PROGRESS'
IMPORT_IN_PROGRESS = 'IMPORT_IN_PROGRESS'
IMPORT_COMPLETE = 'IMPORT_COMPLETE'
IMPORT_ROLLBACK_IN_PROGRESS = 'IMPORT_ROLLBACK_IN_PROGRESS'
IMPORT_ROLLBACK_FAILED = 'IMPORT_ROLLBACK_FAILED'
IMPORT_ROLLBACK_COMPLETE = 'IMPORT_ROLLBACK_COMPLETE'

STACK_STATUS_FILTERS = [
    CREATE_IN_PROGRESS,
    CREATE_FAILED,
    CREATE_COMPLETE,
    ROLLBACK_IN_PROGRESS,
    ROLLBACK_FAILED,
    ROLLBACK_COMPLETE,
    DELETE_IN_PROGRESS,
    DELETE_FAILED,
    DELETE_COMPLETE,
    UPDATE_IN_PROGRESS,
    UPDATE_COMPLETE_CLEANUP_IN_PROGRESS,
    UPDATE_COMPLETE,
    UPDATE_ROLLBACK_IN_PROGRESS,
    UPDATE_ROLLBACK_FAILED,
    UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS,
    UPDATE_ROLLBACK_COMPLETE,
    REVIEW_IN_PROGRESS,
    IMPORT_IN_PROGRESS,
    IMPORT_COMPLETE,
    IMPORT_ROLLBACK_IN_PROGRESS,
    IMPORT_ROLLBACK_FAILED,
    IMPORT_ROLLBACK_COMPLETE
]

STACK_STATUS_FILTERS_TUPLE = (
    CREATE_IN_PROGRESS,
    CREATE_FAILED,
    CREATE_COMPLETE,
    ROLLBACK_IN_PROGRESS,
    ROLLBACK_FAILED,
    ROLLBACK_COMPLETE,
    DELETE_IN_PROGRESS,
    DELETE_FAILED,
    DELETE_COMPLETE,
    UPDATE_IN_PROGRESS,
    UPDATE_COMPLETE_CLEANUP_IN_PROGRESS,
    UPDATE_COMPLETE,
    UPDATE_ROLLBACK_IN_PROGRESS,
    UPDATE_ROLLBACK_FAILED,
    UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS,
    UPDATE_ROLLBACK_COMPLETE,
    REVIEW_IN_PROGRESS,
    IMPORT_IN_PROGRESS,
    IMPORT_COMPLETE,
    IMPORT_ROLLBACK_IN_PROGRESS,
    IMPORT_ROLLBACK_FAILED,
    IMPORT_ROLLBACK_COMPLETE
)

# Filter types
EXACTLY = 'exactly'
CONTAINS = "contains"
STARTS_WITH = "startswith"
ENDS_WITH = "endswith"

STRING_MATCH_CONDITIONS = [
                        EXACTLY,
                        CONTAINS,
                        STARTS_WITH,
                        ENDS_WITH]

# Errror codes
ERC_PROFILE_NOTFOUND = 1
ERC_PROFILE_INVALID = 2
ERC_STACK_NOTFOUND = 11

# Error message
ERM_PROFILE_NOTFOUND = 'The profile is not found!'
ERM_PROFILE_INVALID = 'The credential token is invalid or expired!'
ERM_STACK_NOTFOUND = "The stack does not exist."

# Colors
FG_ERROR = 'red'
BG_ERROR = 'black'

# Others
ALL = '*'
DELIM = ','
NULL = 'NULL'